### ISSUE TITLE
Add dark mode

### ISSUE THREAD

**Issue by nolanlawson** [missive/emoji-mart#293]
It may be nice to have an optional dark mode.

**Comment by darwin2k** [comment]
you can try to overwrite CSS:
```
.emoji-mart, .emoji-mart-category-label span {
  @include themify($themes) {
    background-color: themed('colorBackground');
    color: themed('colorText');
  }
}
```

**Comment by nolanlawson** [comment]
fixed by https://github.com/missive/emoji-mart/pull/391

**Comment by santoshnaagula** [comment]
you can add darkmode true or false, it will reflect

[darkMode]="false"

**Comment by beqacrc** [comment]
at the end you can use this solution

```scss
@use "../../abstract/palette.scss" as *;

@mixin emoji-mart-on-dark {
  .emoji-mart {
    background-color: $clr-main-primary;

    .emoji-mart-preview-name {
      color: #ccc;
    }

    .emoji-mart-category-label {
      background-color: unset;
    }

    .emoji-mart-category .emoji-mart-emoji:hover:before,
    .emoji-mart-emoji-selected:before {
      background-color: $clr-blue-primary;
    }
  }
}


```
