### ISSUE TITLE
Manually set text-align values destroy layout

### ISSUE THREAD

**Issue by rugk** [missive/emoji-mart#318]
## How it should look like

(without text-align)

```css
body * {
  text-align: unset;
}
```

![grafik](https://user-images.githubusercontent.com/11966684/54865209-3b632d80-4d62-11e9-9008-de273dd6807e.png)

## How looks in (explicitly set) LTR mode

(without text-align)

```css
body * {
  text-align: left;
}
```

![grafik](https://user-images.githubusercontent.com/11966684/54865232-9f85f180-4d62-11e9-8324-d546d5c78cf9.png)

## How looks in RTL mode

(without text-align)

```css
body * {
  text-align: right;
}
```

![grafik](https://user-images.githubusercontent.com/11966684/54865221-79605180-4d62-11e9-9639-4742cc8fa7cd.png)

## Issues with that

* In my use-case I inherited that style (from the browser) and thus it broke the display (in a WebExtension of Firefox, see [details here](https://github.com/rugk/awesome-emoji-picker/blob/d86b4e74ac00f3c24958f60d77b1b09b2616d56b/src/popup/index.css#L2-L3))
* In general, this can be an internationalisation (i18n) issue, as it looks kinda broken for in RTL mode
* However, it's even more fun, that explicitly set "LTR mode" also badly affects the top category selector
