### ISSUE TITLE
Config option to show/hide 'emoji-mart-bar'

### ISSUE THREAD

**Issue by dineshvgp** [missive/emoji-mart#42]
In my case I don't want to render the whole `.emoji-mart-bar .emoji-mart-preview` dom. Could you please make it configurabe or Shall I make a PR?

**Comment by EtienneLem** [comment]
I can add an option, but in the meantime you can add this to your css:

```css
.emoji-mart-scroll {
  border-bottom: 0;
  margin-bottom: 6px;
}

.emoji-mart-scroll + .emoji-mart-bar {
  display: none;
}
```
